--- # Ansible Conditional example
- hosts: all
  vars:
    target_file: /home/cloud_user/hostname
  tasks:
    - name: Gather file information
      stat: 
        path: "{{ target_file }}"
      register: hostname
    - name: Rename hostname when found
      command: mv "{{ target_file }}" /home/cloud_user/net-info
      when: hostname.stat.exists

- hosts: Debain
  tasks:
    - name: "shutdown debian flavored systems"
      command: /sbin/shutdown -t now
      when: ansible_facts['os_family'] == "Debian"
