--- # Ansible Facts example
- hosts: web
  tasks:
    - name: create file
      lineinfile:
        path: /home/cloud_user/hostname
        create: yes
        line: "{{ ansible_hostname }}"
    - name: access magic variable
      lineinfile:
        path: /home/cloud_user/hostname
        line: "{{ hostvars['kmurugan1c']['ansible_default_ipv4']['address']['alias']}}"
