--- # template
- hosts: all
  gather_facts: no
  vars:
    code_name: Ball
    version: "2.0"
  tasks:
    - name: deploy config file
      template: 
        src: config.j2
        dest: /opt/config
  