---
- hosts: all
  tasks:
    - name: Create working directory
      file:  
        name: "{{ working_dir }}"
        state: directory
    - name: write service_list file
      lineinfile:
        path: "{{ working_dir }}/services.txt"
        create: yes
        line: "{{ service_list }}"
      