---
- hosts: all
  tasks:
    - name: Create working directory
      file:  
        name: "{{ working_dir }}"
        state: directory
    - name: create nfs directory
      file: 
        path: /mnt/nfs
        state: directory        
    - name: create cifs directory
      file: 
        path: /mnt/cifs
        state: directory
    - name: write service_list file
      lineinfile:
        path: "{{ working_dir }}/services.txt"
        create: yes
        line: "{{ service_list }}"
    - name: View share property
      command: ls -la "{{ nfs_dir['nfs']['cifs'] }}"
      register: cmd_output
    - name: write command module output to file
      copy:
        content: "{{ cmd_output }}"
        dest: "{{ working_dir }}/cmd output.txt"      